name: Windows Test Workflow - Flutter Create to CI

on:
  push:
    branches:
      - main
    paths:
      - '**/windows/**'
      - '**/lib/**'
      - '**/pubspec.yaml'
      - '**/pubspec.lock'
      - '.github/workflows/windows_test_workflow.yml'
      - '.github/workflows/ci_windows.yml'
  pull_request:
    paths:
      - '**/windows/**'
      - '**/lib/**'
      - '**/pubspec.yaml'
      - '**/pubspec.lock'
      - '.github/workflows/windows_test_workflow.yml'
      - '.github/workflows/ci_windows.yml'
  workflow_dispatch:
    inputs:
      project_name:
        description: "Flutter project name to create"
        required: false
        default: "test_app"
      run_plugin_test:
        type: boolean
        description: "Run plugin integration tests"
        required: false
        default: true

jobs:
  windows-flutter-create-and-test:
    runs-on: windows-latest
    timeout-minutes: 45
    strategy:
      matrix:
        windows-version: [10, 11]
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        timeout-minutes: 10
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Create Flutter project
        timeout-minutes: 5
        run: |
          flutter create ${{ inputs.project_name || 'test_app' }}
          cd ${{ inputs.project_name || 'test_app' }}
          echo "Created Flutter project: ${{ inputs.project_name || 'test_app' }}"
          flutter --version
          flutter doctor

      - name: Add gal plugin dependency
        timeout-minutes: 5
        run: |
          cd ${{ inputs.project_name || 'test_app' }}
          # Add the local gal plugin
          echo "  gal:" >> pubspec.yaml
          echo "    path: ../" >> pubspec.yaml
          flutter pub get

      - name: Build Windows app with gal plugin
        if: ${{ inputs.run_plugin_test }}
        id: build-windows-app
        timeout-minutes: 15
        run: |
          cd ${{ inputs.project_name || 'test_app' }}
          flutter build windows --release

      - name: Run existing example integration tests
        timeout-minutes: 15
        run: |
          cd example
          flutter test integration_test/integration_test.dart windows

      - name: Clean up created project
        if: always()
        run: |
          if (Test-Path "${{ inputs.project_name || 'test_app' }}") {
            Remove-Item -Recurse -Force "${{ inputs.project_name || 'test_app' }}"
            echo "Cleaned up created project: ${{ inputs.project_name || 'test_app' }}"
          }
